### ISSUE TITLE
Updating v1.1.2

### ISSUE THREAD

**Issue by martonboti** [JuanMaRuiz/isbn-util#13]
Hi,
can you update the v1.1.2 version to include your latest fixes?

**Comment by JuanMaRuiz** [comment]
Hi @martonboti  thanks for opening this issue. 

Is not possible for you (or your project) to use the [latest version](https://github.com/JuanMaRuiz/isbn-util/releases/tag/v2.0.1) of this package?

**Comment by martonboti** [comment]
It wasn't before, but it has been solved.
Thanks.
