### ISSUE TITLE
isbn13 not valid

### ISSUE THREAD

**Issue by bitboxer** [JuanMaRuiz/isbn-util#3]
I just tried your library and sadly `978-34-2628-155-0` was returned as "invalid ISBN", but it is a real ISBN of a real book.

**Comment by JuanMaRuiz** [comment]
Hi @bitboxer !! First of all, many thanks for trying this utility and for take the time to open this issue. I’ll check the library and I will try to fix this issue. 

Cheers.

**Comment by JuanMaRuiz** [comment]
A [new version](https://github.com/JuanMaRuiz/isbn-util/pull/8) has been released to fix this issue. 

@bitboxer fell free to reopen the issue if it doesn't fix the issue.

Best regards

**Comment by zxxz** [comment]
Hello @JuanMaRuiz , thank you for the library!

Unfortunately though there are a bunch of valid ISBN-13 that `validate` thinks are invalid.

For example: 
978-1-40-208500-0
978-1-40-208499-7
978-9-81-136248-4
978-2-27-509083-2
...

Is this something you are willing to fix?

Thanks!

**Comment by JuanMaRuiz** [comment]
Hi @zxxz  I have created a [new issue](https://github.com/JuanMaRuiz/isbn-util/issues/11) to fix this error. Please, if you have any change review my comment and try to answer my questions.

Regards

**Comment by zxxz** [comment]
[Done](https://github.com/JuanMaRuiz/isbn-util/issues/11#issuecomment-927608891)
