### ISSUE TITLE
isbn10 is not valid when ending in X

### ISSUE THREAD

**Issue by bitboxer** [JuanMaRuiz/isbn-util#4]
The "X" special case for isbn10 is not covered: 006095485X

**Comment by bitboxer** [comment]
Maybe [this](https://stackoverflow.com/posts/23161438/revisions) answer clears it for you

**Comment by JuanMaRuiz** [comment]
Many thanks @bitboxer for opening the issue. I didn’t know this special case. I will fix it asap. 

Cheers.

**Comment by JuanMaRuiz** [comment]
A [new version](https://www.npmjs.com/package/isbn-util) has been generated with the fix.

Feel free to reopen the issue if necessary.

Cheers.

**Comment by bitboxer** [comment]
Awesome. Thank you!
