### ISSUE TITLE
adding a es6 version?

### ISSUE THREAD

**Issue by bitboxer** [JuanMaRuiz/isbn-util#6]
It would be amazing to have an es6 version so that I could write `import {validator} from 'isbn-util'`. Do you think you would like to add that? I could help you and create the PR for this.

Or you could look at [this](https://github.com/bitboxer/jsx-no-react/blob/main/rollup.config.js) config I am using for most projects to achieve this. You can add several output formats that way.

**Comment by JuanMaRuiz** [comment]
Hi!! @bitboxer very good idea! That is the next enhancement for this utility that I had planned. But I would like to maintain both, `require` and esm imports.

I have not started yet to make this task so if you want to contribute and make a PR adding this enhancement it will be very welcome.

Cheers!!

**Comment by JuanMaRuiz** [comment]
Hi @bitboxer , finally this package has been publish as ESModule [v.2.2.0](https://github.com/JuanMaRuiz/isbn-util/pull/10)

Regards

**Comment by bitboxer** [comment]
Thank you!
